In [1]:
import numpy as np

In [20]:
# arr = np.array([i for i in range(1,10)])
arr = np.random.randint(1,20,16).reshape(4,4)
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [21]:
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [23]:
np.sum(arr,axis=1)

array([10, 26])

In [25]:
arr_3d = np.random.randint(1, 8, size=(2, 2, 2))

print("Shape:", arr_3d.shape)
print("\nFull 3D Array:\n", arr_3d)

Shape: (2, 2, 2)

Full 3D Array:
 [[[7 2]
  [2 3]]

 [[4 3]
  [7 6]]]


In [26]:
np.sum(arr_3d,axis=0)

array([[11,  5],
       [ 9,  9]])