In [21]:
import numpy as np

In [38]:
arr = np.random.randint(1,20,16).reshape(4,4)

In [39]:
arr

array([[12,  3, 11,  6],
       [15,  4, 19,  9],
       [ 4,  8,  8, 19],
       [19,  4,  6, 14]])

In [24]:
for i in arr:
  print(i)

[ 7 11 10  9]
[17 14  6 10]
[11 12 15  8]
[ 2 16 18  8]


In [29]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [37]:
arr1 = np.arange(16).reshape(4,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
arr.shape


(4, 4, 4)

In [35]:
arr1.shape

(4, 4)

In [36]:
np.hstack((arr,arr1))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

In [25]:
arr = np.arange(0,64).reshape(4,4,4)

In [26]:
arr1 = np.arange(1,13).reshape(3,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
arr1.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [28]:
arr2 = np.arange(16).reshape(4,3)

ValueError: cannot reshape array of size 16 into shape (4,3)

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
np.hstack((arr1,arr2))

In [ ]:
np.concatenate((arr1,arr2),axis=1)

In [ ]:
np.append(arr2,7)