In [1]:
import numpy as np


In [41]:
arr = np.array([1,2,3,4,5])

In [42]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [43]:
arr0 = np.linspace(1,21,11)
arr0

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21.])

In [44]:
arr2 = np.arange(1,13).reshape(3,4)

In [45]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
arr2.astype(float)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
ran = np.random.random([3,4])

In [15]:
ran2 = np.random.randint(1,100,16).reshape(4,4)

In [16]:
ran2

array([[17, 66, 24, 50],
       [85, 96, 70, 40],
       [81, 45, 11, 73],
       [51, 99, 15, 71]])

In [17]:
arr3 = np.linspace(-2,20,7)

In [18]:
arr3

array([-2.        ,  1.66666667,  5.33333333,  9.        , 12.66666667,
       16.33333333, 20.        ])

In [25]:
arr3 = np.array([
    # Box 1
    [[1, 2],
     [3, 4]],

    # Box 2
    [[5, 6],
     [7, 8]]
])

In [26]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [27]:
arr3.sum(axis=0)

array([[ 6,  8],
       [10, 12]])

In [29]:
arr3.sum(axis=2)

array([[ 3,  7],
       [11, 15]])