In [180]:
import numpy as np

In [ ]:
arr = np.random.randint(1,10,9)

In [182]:
arr


array([9, 1, 2, 7, 6, 8, 2, 8, 9])

In [183]:
arr.reshape(3,3)

array([[9, 1, 2],
       [7, 6, 8],
       [2, 8, 9]])

In [184]:
arr[arr % 2 != 0]

array([9, 1, 7, 9])

In [185]:
arr

array([9, 1, 2, 7, 6, 8, 2, 8, 9])

In [186]:
arr[arr % 2!=0]=-1

In [187]:
a=[1,2,3,4,5,6,7,8,9]

In [188]:
a=np.array([[1,2,3],[8,7,6]])

In [189]:
a


array([[1, 2, 3],
       [8, 7, 6]])

In [190]:
a[1:2,::-1]

array([[6, 7, 8]])

In [191]:
a[a>5]

array([8, 7, 6])

In [192]:
a1=np.array([1,3,5,7,6,10,4,9])

In [193]:
np.where(a1>5)

(array([3, 4, 5, 7]),)

In [194]:
a[2:2]

array([], shape=(0, 3), dtype=int64)

In [195]:
a[1,2]

np.int64(6)

Set2

In [196]:
arr=np.array([1,2,3,4,5,65,6,7])

In [197]:
(a-np.min(a))/(np.max(a)-np.min(a))

array([[0.        , 0.14285714, 0.28571429],
       [1.        , 0.85714286, 0.71428571]])

In [198]:
arr1=np.zeros((5,5))

In [199]:
arr1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [200]:
arr1[0]=1

In [201]:
arr1[4]=1

In [202]:
arr1

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [203]:
arr1[:,0] = 1

In [204]:
arr1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [205]:
arr1[:,4] = 1

In [206]:
arr1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [207]:
a=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

In [208]:
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [209]:
a2=np.array([2,3,4])

In [210]:
a+a2

array([[ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [211]:
a*a2

array([[ 2,  6, 12],
       [ 8, 15, 24],
       [14, 24, 36]])

In [212]:
a-a2

array([[-1, -1, -1],
       [ 2,  2,  2],
       [ 5,  5,  5]])

Set 3


In [227]:
b=np.array([1,2,3,4,5,6])
c=np.array([9,2,8,4,5,6])

In [230]:
b[np.isin(b,c)]

array([2, 4, 5, 6])

In [229]:
np.intersect1d(b,c)

array([2, 4, 5, 6])

In [235]:
arr = np.random.randint(1,10,9).reshape(3,3)
arr

array([[1, 5, 2],
       [6, 9, 7],
       [2, 6, 9]])

In [234]:
arr - np.mean(arr,axis=1)

array([[-1.        , -1.66666667,  2.33333333],
       [-2.        ,  2.33333333,  1.33333333],
       [ 0.        , -1.66666667,  0.33333333]])

In [238]:
arr[:,-1]

array([2, 7, 9])