In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5,6,7])

In [3]:
arr1[0]

np.int64(1)

In [41]:
arr1[-2]

np.int64(6)

In [4]:
arr1[1:5]

array([2, 3, 4, 5])

In [42]:
arr1[1:5:2]

array([2, 4])

In [7]:
arr1[-4:-1]

array([4, 5, 6])

In [8]:
arr1[:4]

array([1, 2, 3, 4])

In [11]:
arr1[[1,3,5]] # gives values at index 1,3 5          integer indexing

array([2, 4, 6])

In [13]:
arr1>2

array([False, False,  True,  True,  True,  True,  True])

In [14]:
arr1[arr1>2]

array([3, 4, 5, 6, 7])

In [17]:
arr2 = np.random.randint(1,20,16).reshape(4,4)

In [18]:
arr2

array([[ 1, 15,  1,  2],
       [16,  3, 14, 12],
       [ 5,  2,  1,  4],
       [11, 12, 10, 15]])

In [19]:
arr2[2]

array([5, 2, 1, 4])

In [21]:
arr2[1,2]

np.int64(14)

In [22]:
arr2[1:3, 2:4]

array([[14, 12],
       [ 1,  4]])

In [23]:
arr2[::2,::2]

array([[1, 1],
       [5, 1]])

In [25]:
arr2[[1,2,3],[1,2,3]]

array([ 3,  1, 15])

In [26]:
arr2[[0,0,3,3],[0,3,0,3]]

array([ 1,  2, 11, 15])

In [50]:
arr = np.array([
    # Box 1 (Now has 3 rows and 4 columns)
    [[1,  2,  9,  0],
     [3,  4, 10,  1],
     [5,  6, 11,  2]],

    # Box 2 (Must match the same dimensions: 3 rows and 4 columns)
    [[7,  8, 12,  3],
     [9,  10, 13, 4],
     [11, 12, 14, 5]]
])

print(arr.shape)  # Output will be: (2, 3, 4)

(2, 3, 4)


In [53]:
arr[[0,1],[0,1]]

array([[ 1,  2,  9,  0],
       [ 9, 10, 13,  4]])

In [51]:
arr[::2, ::2]

array([[[ 1,  2,  9,  0],
        [ 5,  6, 11,  2]]])

In [37]:
arr.shape

(2, 3, 4)

In [38]:
arr[::, 0:2, 1:3]

array([[[ 2,  9],
        [ 4, 10]],

       [[ 8, 12],
        [10, 13]]])

In [40]:
i_matrix = [0,0,0,0,1,1,1,1]
i_rows = [0, 0, 2, 2, 0, 0, 2, 2]
i_cols = [0, 2, 0, 2, 0, 2, 0, 2]
arr[i_matrix, i_rows, i_cols]

array([ 1,  9,  5, 11,  7, 12, 11, 14])

In [56]:
arr5 = np.arange(0,64).reshape(4,4,4)

In [57]:
arr5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [58]:
arr5[::,0,0]

array([ 0, 16, 32, 48])

In [67]:
arr5[ ::, ::3, ::3]

array([[[ 0,  3],
        [12, 15]],

       [[16, 19],
        [28, 31]],

       [[32, 35],
        [44, 47]],

       [[48, 51],
        [60, 63]]])

In [66]:
arr5[ ::, [0,0,3,3], [0,3,0,3]]

array([[ 0,  3, 12, 15],
       [16, 19, 28, 31],
       [32, 35, 44, 47],
       [48, 51, 60, 63]])