In [3]:
import numpy as np

In [36]:
arr = np.random.randint(1,20,16).reshape(4,4)

In [37]:
arr

array([[14, 13,  6,  4],
       [ 8, 18, 15, 19],
       [18, 19, 14,  9],
       [ 6,  6, 10, 13]])

In [38]:
np.sort(arr,axis=0)

array([[ 6,  6,  6,  4],
       [ 8, 13, 10,  9],
       [14, 18, 14, 13],
       [18, 19, 15, 19]])

In [39]:
np.sort(arr,axis= 1)

array([[ 4,  6, 13, 14],
       [ 8, 15, 18, 19],
       [ 9, 14, 18, 19],
       [ 6,  6, 10, 13]])

In [40]:
np.max(arr)

np.int64(19)

In [41]:
np.max(arr,axis=0)

array([18, 19, 15, 19])

In [42]:
np.max(arr,axis = 1)

array([14, 19, 19, 13])

In [43]:
np.min(arr,axis=0)

array([6, 6, 6, 4])

In [44]:
np.sum(arr)

np.int64(192)

In [45]:
np.sum(arr,axis=1)

array([37, 60, 60, 35])

In [46]:
np.prod(arr,axis=1)

array([ 4368, 41040, 43092,  4680])

In [47]:
np.average(arr)

np.float64(12.0)

In [48]:
np.std(arr)

np.float64(4.937104414532874)

In [49]:
np.var(arr)

np.float64(24.375)

In [50]:
arr1 = np.linspace(2,20,10)

In [51]:
arr1

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [52]:
np.sin(arr1)

array([ 0.90929743, -0.7568025 , -0.2794155 ,  0.98935825, -0.54402111,
       -0.53657292,  0.99060736, -0.28790332, -0.75098725,  0.91294525])

In [53]:
np.tan(arr1)

array([-2.18503986,  1.15782128, -0.29100619, -6.79971146,  0.64836083,
       -0.63585993,  7.24460662,  0.30063224, -1.13731371,  2.23716094])

In [54]:
np.pow(arr1,2)

array([  4.,  16.,  36.,  64., 100., 144., 196., 256., 324., 400.])

In [55]:
np.log(2,arr1)

array([0.69314718, 0.69314718, 0.69314718, 0.69314718, 0.69314718,
       0.69314718, 0.69314718, 0.69314718, 0.69314718, 0.69314718])

In [56]:
np.exp(arr)

array([[1.20260428e+06, 4.42413392e+05, 4.03428793e+02, 5.45981500e+01],
       [2.98095799e+03, 6.56599691e+07, 3.26901737e+06, 1.78482301e+08],
       [6.56599691e+07, 1.78482301e+08, 1.20260428e+06, 8.10308393e+03],
       [4.03428793e+02, 4.03428793e+02, 2.20264658e+04, 4.42413392e+05]])

In [57]:
np.round(arr)

array([[14, 13,  6,  4],
       [ 8, 18, 15, 19],
       [18, 19, 14,  9],
       [ 6,  6, 10, 13]])

In [58]:
np.floor(arr)

array([[14, 13,  6,  4],
       [ 8, 18, 15, 19],
       [18, 19, 14,  9],
       [ 6,  6, 10, 13]])

In [59]:
np.ceil(arr)

array([[14, 13,  6,  4],
       [ 8, 18, 15, 19],
       [18, 19, 14,  9],
       [ 6,  6, 10, 13]])

In [60]:
np.cumsum(arr,axis = 0)

array([[14, 13,  6,  4],
       [22, 31, 21, 23],
       [40, 50, 35, 32],
       [46, 56, 45, 45]])

In [61]:
np.percentile(arr,50)

np.float64(13.0)