In [2]:
import numpy as np

## **Set 1**

1. Create a 3x3 array of matrix of all True Boolean values

In [5]:
arr =  np.array(np.random.randint(1,2,size=(3,3)),dtype=bool)


In [6]:
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

2. Extract odd no from an array

In [7]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[arr % 2!=0]

array([1, 3, 5, 7, 9])

In [ ]:
#replace all odd no with -1

3. replace all odd no with -1

In [ ]:
arr3 = np.copy(arr)
print(arr3)
arr3[arr3 % 2 != 0] = -1
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
arr = np.random.randint(1,20,16).reshape(4,4)

In [ ]:
arr

array([[16, 13, 19,  8],
       [ 9,  2, 13, 18],
       [ 1, 15, 17,  2],
       [ 8, 11, 14,  3]])

4. reverse cols of a 2D array

In [ ]:
arr[:,::-1]

array([[ 8, 19, 13, 16],
       [18, 13,  2,  9],
       [ 2, 17, 15,  1],
       [ 3, 14, 11,  8]])

5. get indices of elements greater than 5 (check where method of numpy)


In [ ]:
row_indices, col_indices = np.where(arr > 5)
print(row_indices)
print(col_indices)

[0 0 0 0 1 1 1 2 2 3 3 3]
[0 1 2 3 0 2 3 1 2 0 1 2]


6. access last row - last column

In [ ]:
arr[-1][-1]

np.int64(1)

In [ ]:
arr[-1,-1]

np.int64(3)

###Set 2


2.1 normalize a NumPy array [ to normalize means scaling the values of an array into a specific range, often [0, 1]]

In [ ]:
arr = np.random.random(20)*50
print(arr)

[19.39537336 24.64101151 22.46401036 18.24994515 44.72426601  8.62552082
 31.75270268 45.35415657 34.89303616  8.69863633 19.08224507 10.22480063
 45.41453725 49.39389422  5.26185763  6.23417468 40.75038398 10.85767206
  5.08999034 35.88980923]


In [ ]:
normalized = (arr - arr.min()) / (arr.max()-arr.min())
print(normalized)

[0.32289216 0.44129342 0.39215551 0.29703827 0.89460007 0.07980178
 0.60181406 0.90881757 0.6726957  0.0814521  0.31582442 0.11589973
 0.91018044 1.         0.00387928 0.02582581 0.80490409 0.1301845
 0.         0.69519424]


2.2 Create a 5×5 array with 1 on border and 0 inside

In [ ]:
arr = np.zeros((6,3),dtype=int)
arr[0] = 1

In [ ]:
arr[0] = 1
arr[:,0] = 1
arr[:,len(arr[0])-1] = 1
arr[len(arr)-1] = 1
print(arr)

[[1 1 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]
 [1 1 1]]


 2.3 Create a random array of 10×10: perform stats (min, max, mean, std)

In [ ]:
arr = np.random.randint(0,10,100).reshape(10,10)
print(arr)

[[6 8 8 1 2 3 4 9 0 6]
 [2 2 0 2 6 1 2 2 2 6]
 [6 5 2 0 0 8 4 9 3 5]
 [2 9 0 3 7 6 1 2 9 7]
 [0 2 8 2 9 2 9 5 3 9]
 [8 9 4 0 2 3 4 6 8 6]
 [4 6 9 8 5 7 5 3 9 6]
 [6 8 6 5 3 8 1 3 6 9]
 [3 1 1 0 4 3 1 5 4 1]
 [6 7 8 2 2 2 1 0 2 1]]


In [ ]:
print(arr.min())
print(arr.max())
print(arr.mean())
print(arr.std())

0
9
4.3
2.9


2.4 Broadcast a 1D array over a 2D array [all possible scenarios]

In [ ]:
arr1 = np.random.randint(0,10,16).reshape(4,4)
print(arr1)

[[4 9 2 3]
 [9 0 2 4]
 [6 6 2 6]
 [0 6 5 6]]


In [ ]:
arr2 = np.random.randint(0,5,4)
print(arr2)

[2 0 3 3]


In [ ]:
arr1 + arr2

array([[ 6,  9,  5,  6],
       [11,  0,  5,  7],
       [ 8,  6,  5,  9],
       [ 2,  6,  8,  9]])

In [ ]:

result_rows = arr1 + arr2[:, np.newaxis]
print("arr1 = ",arr1)
print("arr2 = ",arr2)

print("Scenario 2 (Across Columns):\n", result_rows)

arr1 =  [[4 9 2 3]
 [9 0 2 4]
 [6 6 2 6]
 [0 6 5 6]]
arr2 =  [2 0 3 3]
Scenario 2 (Across Columns):
 [[ 6 11  4  5]
 [ 9  0  2  4]
 [ 9  9  5  9]
 [ 3  9  8  9]]


Set 3

•	Find common elements between two arrays [with and without using intersect1d, use isin() instead]

•	Subtract row mean from each row of a 2D array

•	Given a 4×4 array, swap the first half rows with the second half rows

•	Given a 1D array of random numbers, find the indices of the 5 largest values (no sorting/ check argsort() instead).

•	From a 2D NumPy array, extract only the unique rows (no duplicates hint: check unique method).

1. Find common elements between two arrays [with and without using intersect1d, use isin() instead]

In [ ]:
arr1[np.isin(arr1,arr2)]

array([2, 3, 0, 2, 2, 0])

In [ ]:
arr1

array([[4, 9, 2, 3],
       [9, 0, 2, 4],
       [6, 6, 2, 6],
       [0, 6, 5, 6]])

2. Subtract row mean from each row of a 2D array

In [ ]:
mn = np.mean(arr1,axis = 1)
print(mn)

[4.5  3.75 5.   4.25]


In [ ]:
mn = mn.reshape(-1,1)
mn

array([[4.5 ],
       [3.75],
       [5.  ],
       [4.25]])

In [ ]:
arr1 - mn

array([[-0.5 ,  4.5 , -2.5 , -1.5 ],
       [ 5.25, -3.75, -1.75,  0.25],
       [ 1.  ,  1.  , -3.  ,  1.  ],
       [-4.25,  1.75,  0.75,  1.75]])

3. Given a 4×4 array, swap the first half rows with the second half rows

In [ ]:
arr = np.random.randint(0,10,16).reshape(4,4)

In [ ]:
arr

array([[5, 8, 0, 1],
       [2, 1, 9, 0],
       [4, 6, 0, 2],
       [8, 1, 4, 1]])