In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,3,4,5,2,7])

In [3]:
arr1

array([1, 3, 4, 5, 2, 7])

In [8]:
arr1 + 5           # scaler addition

array([ 6,  8,  9, 10,  7, 12])

In [11]:
arr1 * 2

array([ 2,  6,  8, 10,  4, 14])

In [20]:
arr2 = np.array([1,3,4])

In [21]:
arr1

array([1, 3, 4, 5, 2, 7])

In [22]:
arr2

array([1, 3, 4])

In [23]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (6,) (3,) 

In [25]:
arr2 = np.array([
    [0,2,6],
    [3,8,15],
    [6,7,2]
])

In [26]:
arr = np.array([10,20,30])
arr2  * arr

array([[  0,  40, 180],
       [ 30, 160, 450],
       [ 60, 140,  60]])

In [29]:
arr3 = np.array([
    [[1,2,3],
     [4,5,6]],

    [[7,8,9],
     [10,11,12]]
])

In [30]:
arr3.shape

(2, 2, 3)

In [31]:
arr3 + np.array([10,20,30])

array([[[11, 22, 33],
        [14, 25, 36]],

       [[17, 28, 39],
        [20, 31, 42]]])

In [32]:
arr4 = np.arange(10,16).reshape(2,3)

In [36]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
arr4

array([[10, 11, 12],
       [13, 14, 15]])

In [34]:
arr4.shape

(2, 3)

In [35]:
arr3 + arr4

array([[[11, 13, 15],
        [17, 19, 21]],

       [[17, 19, 21],
        [23, 25, 27]]])

In [40]:
arr4 = np.arange(10,12).reshape(2,1)

In [41]:
arr4

array([[10],
       [11]])

In [39]:
arr3 + arr4

array([[[11, 12, 13],
        [15, 16, 17]],

       [[17, 18, 19],
        [21, 22, 23]]])

In [64]:
arr9 = np.arange(1,13).reshape(2,2,3)
print(f"arr9 = {arr9}\n\n")

arr10 = np.array([10])
print(f"arr10 = {arr10}\n\n")

res = arr9 * arr10
print(f"Result: {res}")

arr9 = [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


arr10 = [10]


Result: [[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]


In [4]:
arr1 = np.array([1,3,4,5,2,7])

In [6]:
def square(n):
  return n*2
squares = np.vectorize(square)
squares(arr1)


array([ 2,  6,  8, 10,  4, 14])