In [2]:
import numpy as np

In [4]:
virat_runs = np.array([72,45,88,101])
virat_runs

array([ 72,  45,  88, 101])

In [5]:
team_runs= np.array([
    [72,45,88],
    [55,60,47],
    [30,75,50]
])
team_runs

array([[72, 45, 88],
       [55, 60, 47],
       [30, 75, 50]])

In [7]:
player_ages = np.array((35,65,31))
player_ages

array([35, 65, 31])

In [16]:
# all becomes float
strike_rates = np.array([120,135.5,4])
print(strike_rates,strike_rates.dtype)

[120.  135.5   4. ] float64


In [24]:
np.array([3,4,6],dtype=float)


array([3., 4., 6.])

In [25]:
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.empty((2,2))  # possible garbage values

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 2.89270636e-307]])

In [ ]:
arr = np.arange(22,55,1)  # start included but end not included
arr

array([22.6, 23.6, 24.6, 25.6, 26.6, 27.6, 28.6, 29.6, 30.6, 31.6, 32.6,
       33.6, 34.6, 35.6, 36.6, 37.6, 38.6, 39.6, 40.6, 41.6, 42.6, 43.6,
       44.6, 45.6, 46.6, 47.6, 48.6, 49.6, 50.6, 51.6, 52.6, 53.6, 54.6])

In [35]:
arr[1]

np.int64(23)

In [47]:
 
arr2 = np.linspace(30,50,5)                 # start and end both included       , returns float values
arr2

array([30., 35., 40., 45., 50.])

In [50]:
a=np.linspace(6,17,9)
a

array([ 6.   ,  7.375,  8.75 , 10.125, 11.5  , 12.875, 14.25 , 15.625,
       17.   ])

In [ ]:
b= np.random.seed(42)
print(b)

None


In [55]:
b= np.random.randint(1,40,10)
print(b)

[38 20  6 14 22 17 27 21 16  1]


In [ ]:
np.random.seed(42)
# n  randomly uniform between a and b
# uniform = every value in the range is equally likely 
# 100 = lower limit   200 = upper limit  10 = how many nos
strike_rates = np.random.uniform(100,200,100)
strike_rates

array([164.20316462, 108.4139965 , 116.16287141, 189.85541885,
       160.64290597, 100.91970516, 110.14715429, 166.35017691,
       100.50615838, 116.08080514, 154.87337894, 169.18951977,
       165.19612595, 122.42693095, 171.21792213, 123.72490875,
       132.53996982, 174.64914051, 164.9632899 , 184.92234105,
       165.76128923, 156.83086033, 109.36747678, 136.77158031,
       126.52023677, 124.39896434, 197.30105548, 139.30977247,
       189.20465552, 163.1138626 , 179.48113035, 150.26370931,
       157.69038846, 149.25176938, 119.52429878, 172.24521153,
       128.07723624, 102.43159664, 164.54722959, 117.71106794,
       194.04585844, 195.3928577 , 191.48643902, 137.01587003,
       101.54566165, 192.83185626, 142.81841483, 196.6654819 ,
       196.36199771, 185.30094555, 129.44488921, 138.50977286,
       185.11366715, 131.69220052, 116.94927467, 155.68012625,
       193.61547742, 169.60297967, 157.00611701, 109.71764938,
       161.50072267, 199.00538501, 114.00840152, 151.83

In [79]:
np.random.seed(42)
runs = np.random.randint(1,151,(2,3))
runs

array([[103,  93,  15],
       [107,  72,  21]], dtype=int32)

In [101]:
# new way recommanded    random number generator  with its own seed
rng = np.random.default_rng(42)
rng.integers(1,7,10)

array([1, 5, 4, 3, 3, 6, 1, 5, 2, 1])

In [ ]:
np.random.normal(40,5,(2,3))                # NORMAL DISTRIBUTION  40 MEAN  5 SD  (2,3) SHAPE    

array([[41.87849009, 36.99680655, 38.54153125],
       [36.99146694, 49.26139092, 39.93251388]])

In [94]:
economy_scores =   np.random.randn(2,3)
economy_scores

array([[-1.19620662,  0.81252582,  1.35624003],
       [-0.07201012,  1.0035329 ,  0.36163603]])

In [96]:
np.random.rand(5)                 # 5 random no betn 0 and 1

array([0.42754102, 0.02541913, 0.10789143, 0.03142919, 0.63641041])

In [99]:
# randomly pick items
squad = np.array(["virat","rohit","rahul","gill","pint"])
np.random.choice(squad , 3,replace=False)

array(['rohit', 'pint', 'rahul'], dtype='<U5')

In [102]:
sale=[0,5,11,15,20]
sales= np.array(sale)

print(sales.shape)
print(sales.size)
print(sales.dtype)



(5,)
5
int64


In [116]:
store_sales=np.array([
    [1,2,3,4],
    [5.5,6,7,8],
    [9,0,1,2]
])
print(store_sales)

[[1.  2.  3.  4. ]
 [5.5 6.  7.  8. ]
 [9.  0.  1.  2. ]]


In [117]:
print(store_sales.shape)
print(store_sales.size)
print(store_sales.dtype)

(3, 4)
12
float64


In [124]:
a=[5]
b=[10]
temp = a
a=b
b=temp

print (a,b)

[10] [5]


In [164]:
marks = np.array([24, 71, 53, 25, 41, 30, 67, 35, 52, 28])
marks

array([24, 71, 53, 25, 41, 30, 67, 35, 52, 28])

In [165]:

top_batch = marks[0:5]
print(top_batch)

[24 71 53 25 41]


In [149]:
print(marks[0])
print(marks[4])

temp = marks[0].copy()
marks[0]=marks[4]
marks[4]=temp

print(top_batch)

99
99
[99 99 99 99 99]


In [157]:
mmm = marks.copy()
mmm[:] = 99
print(marks)

[51 74 23 74 30 75 78 36 57 43]


In [158]:
top_batch[:] = 99
marks

array([99, 99, 99, 99, 99, 75, 78, 36, 57, 43], dtype=int32)

In [159]:
#conditionasl selection
passed = marks > 35
passed

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [160]:
marks[passed]

array([99, 99, 99, 99, 99, 75, 78, 36, 57, 43], dtype=int32)

In [161]:
marks[ (marks>=50) & (marks < 80)  ]
marks[ (marks<35) | (marks > 90)  ]
marks[~passed]

array([], dtype=int32)

In [ ]:
np.sum(marks<35)            # how many failed

np.int64(4)

In [173]:
# summary/descriptive statistics
sales=np.array([1,2,3,4,56,7,8,9,21,34,5643,43])
sales.std().round(2)

np.float64(1555.02)

In [183]:
ss= np.array([
    [
        [1,2,3,4],
        [5,6,7,8]
       ],
    [
        [9,10,11,12],
        [13,14,15,16]
    ]
])
print(ss.sum())
print()
print(ss.sum(axis=0))
print()
print(ss.sum(axis=1))
print()
print(ss.sum(axis=2))



136

[[10 12 14 16]
 [18 20 22 24]]

[[ 6  8 10 12]
 [22 24 26 28]]

[[10 26]
 [42 58]]


In [189]:
marks  = np.array([78,95,88,67,91])
names = np.array(["amit","neha","raj","oriya","kiran"])
np.sort(marks)

array([67, 78, 88, 91, 95])

In [198]:
order = np.argsort(marks)
order

array([3, 0, 2, 4, 1])

In [192]:
expenses = np.array([2500,3200,np.nan,4100,3900,np.nan,3000])
expenses

array([2500., 3200.,   nan, 4100., 3900.,   nan, 3000.])

In [193]:
expenses.sum()


np.float64(nan)

In [194]:
expenses.sum()

np.float64(nan)

In [195]:
np.nan == np.nan

False

In [197]:
missing = np.isnan(expenses)
missing

array([False, False,  True, False, False,  True, False])

In [ ]:
missing = np.isna(expenses)
clena = expenses[~np.isnan(expences)]
np.nan_to_num(expenses,nan = 0)

filled = np.where(np.isnan(expense),np.nanmean(expendes),expenses)