In [2]:
import numpy as np

In [3]:
virat_runs = np.array([72,45,88,101])
virat_runs

array([ 72,  45,  88, 101])

In [4]:
team_runs= np.array([
    [72,45,88],
    [55,60,47],
    [30,75,50]
])
team_runs

array([[72, 45, 88],
       [55, 60, 47],
       [30, 75, 50]])

In [5]:
player_ages = np.array((35,65,31))
player_ages

array([35, 65, 31])

In [6]:
# all becomes float
strike_rates = np.array([120,135.5,4])
print(strike_rates,strike_rates.dtype)

[120.  135.5   4. ] float64


In [7]:
np.array([3,4,6],dtype=float)


array([3., 4., 6.])

In [8]:
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.empty((2,2))  # possible garbage values

array([[2.12199579e-314, 1.23500155e-311],
       [5.84973725e-321, 6.95293141e-310]])

In [13]:
arr = np.arange(22,55,1)  # start included but end not included
arr

array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54])

In [14]:
arr[1]

np.int64(23)

In [15]:
 
arr2 = np.linspace(30,50,5)                 # start and end both included       , returns float values
arr2

array([30., 35., 40., 45., 50.])

In [16]:
a=np.linspace(6,17,9)
a

array([ 6.   ,  7.375,  8.75 , 10.125, 11.5  , 12.875, 14.25 , 15.625,
       17.   ])

In [17]:
b= np.random.seed(42)
print(b)

None


In [18]:
b= np.random.randint(1,40,10)
print(b)

[39 29 15  8 21 39 19 23 11 11]


In [19]:
np.random.seed(42)
# n  randomly uniform between a and b
# uniform = every value in the range is equally likely 
# 100 = lower limit   200 = upper limit  10 = how many nos
strike_rates = np.random.uniform(100,200,100)
strike_rates

array([137.45401188, 195.07143064, 173.19939418, 159.86584842,
       115.60186404, 115.59945203, 105.80836122, 186.61761458,
       160.11150117, 170.80725778, 102.05844943, 196.99098522,
       183.24426408, 121.23391107, 118.18249672, 118.34045099,
       130.4242243 , 152.47564316, 143.19450186, 129.12291402,
       161.18528947, 113.94938607, 129.21446485, 136.63618433,
       145.60699842, 178.51759614, 119.96737822, 151.42344384,
       159.24145689, 104.64504127, 160.75448519, 117.05241237,
       106.5051593 , 194.88855373, 196.56320331, 180.83973481,
       130.46137692, 109.7672114 , 168.42330265, 144.01524937,
       112.20382348, 149.51769101, 103.43885211, 190.93204021,
       125.87799816, 166.25222844, 131.17110761, 152.00680212,
       154.67102793, 118.48544555, 196.95846278, 177.51328234,
       193.94989416, 189.48273504, 159.78999788, 192.1874235 ,
       108.84925021, 119.59828624, 104.52272889, 132.53303308,
       138.86772897, 127.13490318, 182.87375092, 135.67

In [20]:
np.random.seed(42)
runs = np.random.randint(1,151,(2,3))
runs

array([[103,  93,  15],
       [107,  72,  21]], dtype=int32)

In [21]:
# new way recommanded    random number generator  with its own seed
rng = np.random.default_rng(42)
rng.integers(1,7,10)

array([1, 5, 4, 3, 3, 6, 1, 5, 2, 1])

In [22]:
np.random.normal(40,5,(2,3))                # NORMAL DISTRIBUTION  40 MEAN  5 SD  (2,3) SHAPE    

array([[38.82923313, 38.82931522, 47.89606408],
       [43.83717365, 37.65262807, 42.71280022]])

In [23]:
economy_scores =   np.random.randn(2,3)
economy_scores

array([[-0.46341769, -0.46572975,  0.24196227],
       [-1.91328024, -1.72491783, -0.56228753]])

In [24]:
np.random.rand(5)                 # 5 random no betn 0 and 1

array([0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998])

In [25]:
# randomly pick items
squad = np.array(["virat","rohit","rahul","gill","pint"])
np.random.choice(squad , 3,replace=False)

array(['virat', 'rohit', 'pint'], dtype='<U5')

In [26]:
sale=[0,5,11,15,20]
sales= np.array(sale)

print(sales.shape)
print(sales.size)
print(sales.dtype)



(5,)
5
int64


In [27]:
store_sales=np.array([
    [1,2,3,4],
    [5.5,6,7,8],
    [9,0,1,2]
])
print(store_sales)

[[1.  2.  3.  4. ]
 [5.5 6.  7.  8. ]
 [9.  0.  1.  2. ]]


In [28]:
print(store_sales.shape)
print(store_sales.size)
print(store_sales.dtype)

(3, 4)
12
float64


In [29]:
a=[5]
b=[10]
temp = a
a=b
b=temp

print (a,b)

[10] [5]


In [30]:
marks = np.array([24, 71, 53, 25, 41, 30, 67, 35, 52, 28])
marks

array([24, 71, 53, 25, 41, 30, 67, 35, 52, 28])

In [31]:

top_batch = marks[0:5]
print(top_batch)

[24 71 53 25 41]


In [32]:
print(marks[0])
print(marks[4])

temp = marks[0].copy()
marks[0]=marks[4]
marks[4]=temp

print(top_batch)

24
41
[41 71 53 25 24]


In [33]:
mmm = marks.copy()
mmm[:] = 99
print(marks)

[41 71 53 25 24 30 67 35 52 28]


In [34]:
top_batch[:] = 99
marks

array([99, 99, 99, 99, 99, 30, 67, 35, 52, 28])

In [35]:
#conditionasl selection
passed = marks > 35
passed

array([ True,  True,  True,  True,  True, False,  True, False,  True,
       False])

In [36]:
marks[passed]

array([99, 99, 99, 99, 99, 67, 52])

In [37]:
marks[ (marks>=50) & (marks < 80)  ]
marks[ (marks<35) | (marks > 90)  ]
marks[~passed]

array([30, 35, 28])

In [38]:
np.sum(marks<35)            # how many failed

np.int64(2)

In [39]:
# summary/descriptive statistics
sales=np.array([1,2,3,4,56,7,8,9,21,34,5643,43])
sales.std().round(2)

np.float64(1555.02)

In [40]:
ss= np.array([
    [
        [1,2,3,4],
        [5,6,7,8]
       ],
    [
        [9,10,11,12],
        [13,14,15,16]
    ]
])
print(ss.sum())
print()
print(ss.sum(axis=0))
print()
print(ss.sum(axis=1))
print()
print(ss.sum(axis=2))



136

[[10 12 14 16]
 [18 20 22 24]]

[[ 6  8 10 12]
 [22 24 26 28]]

[[10 26]
 [42 58]]


In [41]:
marks  = np.array([78,95,88,67,91])
names = np.array(["amit","neha","raj","oriya","kiran"])
np.sort(marks)

array([67, 78, 88, 91, 95])

In [42]:
order = np.argsort(marks)
order

array([3, 0, 2, 4, 1])

NameError: name 'true_divide' is not defined

In [ ]:
expenses = np.array([2500,3200,np.nan,4100,3900,np.nan,3000])
expenses

array([2500., 3200.,   nan, 4100., 3900.,   nan, 3000.])

In [ ]:
expenses.sum()


np.float64(nan)

In [ ]:
expenses.sum()

np.float64(nan)

In [ ]:
np.nan == np.nan

False

In [ ]:
missing = np.isnan(expenses)
missing

array([False, False,  True, False, False,  True, False])

In [ ]:
missing = np.isna(expenses)
clena = expenses[~np.isnan(expences)]
np.nan_to_num(expenses,nan = 0)

filled = np.where(np.isnan(expense),np.nanmean(expendes),expenses)